# Generated by Django 6.0.7 on 2026-07-31 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='pincode',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
