# Generated by Django 6.0.7 on 2026-07-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nit', '0002_alter_building_geometry_alter_building_gis_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='gis_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
