# Generated by Django 6.0.7 on 2026-08-05 11:14

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nit', '0003_searchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
