# Generated by Django 6.0.7 on 2026-07-29 07:24

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nit', '0003_alter_building_gis_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=3857),
        ),
        migrations.AlterField(
            model_name='corporation',
            name='total_area',
            field=models.FloatField(default=0),
        ),
    ]
